title = "Tanvi Dadu"
baseURL = "https://tanvidadu.github.io/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "New Delhi, India"
email = "tanvidadu1998@gmail.com"
favicon = "/favicon.ico"
firstName = "Tanvi"
lastName = "Dadu"
profileImage = "img/TechChat.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = true
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/feed/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/tanvidadu"
name = "GitHub"

[[params.handles]]
link = "https://scholar.google.com/citations?user=vz6lRPoAAAAJ&hl=en"
name = "Google Scholar"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
